
spring:
  thymeleaf:
    cache: false
  profiles:
    active: dev
mybatis:
  type-aliases-package: com.qin.pojo
  mapper-locations: classpath:mybatis/config/*.xml

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
